@startuml
set namespaceSeparator ::

class "my_gym_bro::firebase_options.dart::DefaultFirebaseOptions" {
  {static} +FirebaseOptions web
  {static} +FirebaseOptions android
  {static} +FirebaseOptions ios
  {static} +FirebaseOptions currentPlatform
}

"my_gym_bro::firebase_options.dart::DefaultFirebaseOptions" o-- "firebase_core_platform_interface::firebase_core_platform_interface.dart::FirebaseOptions"

class "my_gym_bro::main.dart::AppState" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "my_gym_bro::main.dart::AppState"

class "my_gym_bro::main.dart::MyApp" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "my_gym_bro::main.dart::MyApp"

class "my_gym_bro::models::ejercicio.dart::Ejercicio" {
  +List<EjercicioElement> ejercicio
  +Map<String, dynamic> toJson()
}

class "my_gym_bro::models::ejercicio.dart::EjercicioElement" {
  +String name
  +String tip
  +List<String> muscle
  +String url
  +Map<String, dynamic> toJson()
  +String toString()
}

class "my_gym_bro::models::ejercicio_rutina.dart::EjercicioRutina" {
  +String name
  +String tip
  +List<String> muscle
  +String url
  +List<RowRepKg> listSeries
  +dynamic getListSeries
  +dynamic setListSeries
  +dynamic getName
  +dynamic getTip
  +dynamic getMuscle
  +dynamic getUrl
  +String toJson()
  +Map<String, dynamic> toMap()
  +String toString()
}

class "my_gym_bro::models::listas.dart::Listas" {
  +List<EjercicioElement> ejerciciosList
  +List<EjercicioElement> ejerciciosRutinaList
  +List<String> musculoList
  +List<Pr> prList
  +List<Rutina> rutinasList
  +dynamic getPrList
  +dynamic getMusculoList
  +dynamic getListEjercicioRutina
  +List<Rutina> getRutinasList()
  +void clear()
  +dynamic setRutinasList()
  +void addRutinaList()
  +dynamic setPrList()
  +void addPrList()
  +dynamic setMusculoList()
  +void addMusculoList()
  +List<EjercicioElement> getListEjercicio()
  +dynamic setEjerciosList()
  +void addEjercicioList()
  +dynamic setEjerciosRutinaList()
  +void addEjercicioRutinaList()
  +void removeEjercicioRutinaList()
}

"get::get_state_manager::src::simple::get_controllers.dart::GetxController" <|-- "my_gym_bro::models::listas.dart::Listas"

class "my_gym_bro::models::menu_option.dart::MenuOption" {
  +String route
  +IconData icon
  +AssetImage image
  +String name
  +Widget screen
}

"my_gym_bro::models::menu_option.dart::MenuOption" o-- "flutter::src::widgets::icon_data.dart::IconData"
"my_gym_bro::models::menu_option.dart::MenuOption" o-- "flutter::src::painting::image_resolution.dart::AssetImage"
"my_gym_bro::models::menu_option.dart::MenuOption" o-- "flutter::src::widgets::framework.dart::Widget"

class "my_gym_bro::models::pr.dart::Pr" {
  +String nameEjercicio
  +double peso
  +String? id
  +String? idUser
  +String toJson()
  +Map<String, dynamic> toMap()
}

class "my_gym_bro::models::retos.dart::Reto" {
  +bool completado
  +String nombre
  +Map<String, dynamic> toJson()
}

class "my_gym_bro::models::row_rep_kg.dart::RowRepKg" {
  +int? repes
  +int? kg
  +int? getRepes
  +int? getKg
  +String toJson()
  +Map<String, dynamic> toMap()
  +String toString()
}

class "my_gym_bro::models::rutina.dart::Rutina" {
  +String name
  +String note
  +List<EjercicioRutina>? listEjerciciosRutina
  +String? id
  +String? idUser
  +String setName
  +dynamic getName
  +dynamic getNote
  +dynamic setNote
  +dynamic getListEjerciciosRutina
  +dynamic setListEjerciciosRutina
  +String toJson()
  +Map<String, dynamic> toMap()
  +String toString()
}

class "my_gym_bro::providers::login_form_provider.dart::LoginFormProvider" {
  +GlobalKey<FormState> formKey
  +String email
  +String password
  -bool _isLoading
  +bool isLoading
  +bool isValidForm()
}

"my_gym_bro::providers::login_form_provider.dart::LoginFormProvider" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "my_gym_bro::providers::login_form_provider.dart::LoginFormProvider"

class "my_gym_bro::router::app_routes.dart::AppRoutes" {
  {static} +String initialRoute
  {static} +List<MenuOption> menuOption
  {static} +List<MenuOption> bottomMenuOption
  {static} +Map<String, Widget Function(BuildContext)> getAppRoutes()
  {static} +Route<dynamic> onGenerateRoute()
}

class "my_gym_bro::screens::add_entrenos_screen.dart::AddEntrenosScreen" {
  +Rutina rutina
  +RutinaService rutinaService
  +State<AddEntrenosScreen> createState()
}

"my_gym_bro::screens::add_entrenos_screen.dart::AddEntrenosScreen" o-- "my_gym_bro::models::rutina.dart::Rutina"
"my_gym_bro::screens::add_entrenos_screen.dart::AddEntrenosScreen" o-- "my_gym_bro::service::peticiones_service.dart::RutinaService"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "my_gym_bro::screens::add_entrenos_screen.dart::AddEntrenosScreen"

class "my_gym_bro::screens::add_entrenos_screen.dart::_AddEntrenosScreenState" {
  +List<RowRepKg> list
  +Listas controller
  +String grupoMuscular
  +int numseries
  +EjercicioElement ejercicioElegido
  +List<DropdownMenuItem<String>> dropdownMusculosItems
  +List<DropdownMenuItem<EjercicioElement>> dropdownEjerciciosItems
  +Widget build()
}

"my_gym_bro::screens::add_entrenos_screen.dart::_AddEntrenosScreenState" o-- "my_gym_bro::models::listas.dart::Listas"
"my_gym_bro::screens::add_entrenos_screen.dart::_AddEntrenosScreenState" o-- "my_gym_bro::models::ejercicio.dart::EjercicioElement"
"flutter::src::widgets::framework.dart::State" <|-- "my_gym_bro::screens::add_entrenos_screen.dart::_AddEntrenosScreenState"

class "my_gym_bro::screens::add_pr_screen.dart::AddPrScreen" {
  +State<AddPrScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "my_gym_bro::screens::add_pr_screen.dart::AddPrScreen"

class "my_gym_bro::screens::add_pr_screen.dart::_AddPrScreenState" {
  +Pr pr
  +String ejercicio
  +double kg
  +Listas controller
  +List<DropdownMenuItem<EjercicioElement>> dropdownEjerciciosItems
  +Widget build()
}

"my_gym_bro::screens::add_pr_screen.dart::_AddPrScreenState" o-- "my_gym_bro::models::pr.dart::Pr"
"my_gym_bro::screens::add_pr_screen.dart::_AddPrScreenState" o-- "my_gym_bro::models::listas.dart::Listas"
"flutter::src::widgets::framework.dart::State" <|-- "my_gym_bro::screens::add_pr_screen.dart::_AddPrScreenState"

class "my_gym_bro::screens::amigos_screen.dart::AmigosScreen" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "my_gym_bro::screens::amigos_screen.dart::AmigosScreen"

class "my_gym_bro::screens::check_auth_screen.dart::CheckAuthScreen" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "my_gym_bro::screens::check_auth_screen.dart::CheckAuthScreen"

class "my_gym_bro::screens::detalles_rutina.dart::DetallesRutina" {
  +Rutina rutina
  +State<DetallesRutina> createState()
}

"my_gym_bro::screens::detalles_rutina.dart::DetallesRutina" o-- "my_gym_bro::models::rutina.dart::Rutina"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "my_gym_bro::screens::detalles_rutina.dart::DetallesRutina"

class "my_gym_bro::screens::detalles_rutina.dart::_DetallesRutinaState" {
  +Listas controller
  +Widget build()
}

"my_gym_bro::screens::detalles_rutina.dart::_DetallesRutinaState" o-- "my_gym_bro::models::listas.dart::Listas"
"flutter::src::widgets::framework.dart::State" <|-- "my_gym_bro::screens::detalles_rutina.dart::_DetallesRutinaState"

class "my_gym_bro::screens::editar_ejercicio_rutina.dart::EditarEjercicioRutinaScreen" {
  +Rutina rutina
  +EjercicioRutina ejercicio
  +RutinaService rutinaService
  +State<EditarEjercicioRutinaScreen> createState()
}

"my_gym_bro::screens::editar_ejercicio_rutina.dart::EditarEjercicioRutinaScreen" o-- "my_gym_bro::models::rutina.dart::Rutina"
"my_gym_bro::screens::editar_ejercicio_rutina.dart::EditarEjercicioRutinaScreen" o-- "my_gym_bro::models::ejercicio_rutina.dart::EjercicioRutina"
"my_gym_bro::screens::editar_ejercicio_rutina.dart::EditarEjercicioRutinaScreen" o-- "my_gym_bro::service::peticiones_service.dart::RutinaService"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "my_gym_bro::screens::editar_ejercicio_rutina.dart::EditarEjercicioRutinaScreen"

class "my_gym_bro::screens::editar_ejercicio_rutina.dart::_EditarEjercicioRutinaScreen" {
  +int numseries
  +List<RowRepKg> list
  +String grupoMuscular
  +EjercicioElement grupoEjercicios
  +Listas controller
  +EjercicioElement ejer
  +EjercicioElement ejercicioElegido
  +List<DropdownMenuItem<String>> dropdownMusculosItems
  +List<DropdownMenuItem<EjercicioElement>> dropdownEjerciciosItems
  +Widget build()
}

"my_gym_bro::screens::editar_ejercicio_rutina.dart::_EditarEjercicioRutinaScreen" o-- "my_gym_bro::models::ejercicio.dart::EjercicioElement"
"my_gym_bro::screens::editar_ejercicio_rutina.dart::_EditarEjercicioRutinaScreen" o-- "my_gym_bro::models::listas.dart::Listas"
"flutter::src::widgets::framework.dart::State" <|-- "my_gym_bro::screens::editar_ejercicio_rutina.dart::_EditarEjercicioRutinaScreen"

class "my_gym_bro::screens::ejercicios_screen.dart::EjerciciosScreen" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "my_gym_bro::screens::ejercicios_screen.dart::EjerciciosScreen"

class "my_gym_bro::screens::ejercicio_detail_screen.dart::EjercicioDetailScreen" {
  +EjercicioElement ejercicio
  +Widget build()
}

"my_gym_bro::screens::ejercicio_detail_screen.dart::EjercicioDetailScreen" o-- "my_gym_bro::models::ejercicio.dart::EjercicioElement"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "my_gym_bro::screens::ejercicio_detail_screen.dart::EjercicioDetailScreen"

class "my_gym_bro::screens::entrenos_screen.dart::EntrenosScreen" {
  +State<EntrenosScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "my_gym_bro::screens::entrenos_screen.dart::EntrenosScreen"

class "my_gym_bro::screens::entrenos_screen.dart::_EntrenosScreenState" {
  +String nombreRutina
  +String observacionesRutina
  +Listas controller
  +Rutina rutina
  +Widget build()
  +void showCustomDialog()
}

"my_gym_bro::screens::entrenos_screen.dart::_EntrenosScreenState" o-- "my_gym_bro::models::listas.dart::Listas"
"my_gym_bro::screens::entrenos_screen.dart::_EntrenosScreenState" o-- "my_gym_bro::models::rutina.dart::Rutina"
"flutter::src::widgets::framework.dart::State" <|-- "my_gym_bro::screens::entrenos_screen.dart::_EntrenosScreenState"

class "my_gym_bro::screens::graficos_screen.dart::GrafficsScreen" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "my_gym_bro::screens::graficos_screen.dart::GrafficsScreen"

class "my_gym_bro::screens::home_screen.dart::HomeScreen" {
  +State<HomeScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "my_gym_bro::screens::home_screen.dart::HomeScreen"

class "my_gym_bro::screens::home_screen.dart::_HomeScreenState" {
  -int _selectedIndex
  -void _onItemTapped()
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "my_gym_bro::screens::home_screen.dart::_HomeScreenState"

class "my_gym_bro::screens::inicio_screen.dart::InicioScreen" {
  +State<InicioScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "my_gym_bro::screens::inicio_screen.dart::InicioScreen"

class "my_gym_bro::screens::inicio_screen.dart::_InicioScreenState" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "my_gym_bro::screens::inicio_screen.dart::_InicioScreenState"

class "my_gym_bro::screens::login_screen.dart::LoginScreen" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "my_gym_bro::screens::login_screen.dart::LoginScreen"

class "my_gym_bro::screens::login_screen.dart::_LoginForm" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "my_gym_bro::screens::login_screen.dart::_LoginForm"

class "my_gym_bro::screens::medidas_screen.dart::MeasureScreen" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "my_gym_bro::screens::medidas_screen.dart::MeasureScreen"

class "my_gym_bro::screens::register_screen.dart::RegisterScreen" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "my_gym_bro::screens::register_screen.dart::RegisterScreen"

class "my_gym_bro::screens::register_screen.dart::_LoginForm" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "my_gym_bro::screens::register_screen.dart::_LoginForm"

class "my_gym_bro::screens::retos_screen.dart::RetosScreen" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "my_gym_bro::screens::retos_screen.dart::RetosScreen"

class "my_gym_bro::screens::revisar_pr.dart::RevisarPr" {
  +Listas controller
  +Widget build()
}

"my_gym_bro::screens::revisar_pr.dart::RevisarPr" o-- "my_gym_bro::models::listas.dart::Listas"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "my_gym_bro::screens::revisar_pr.dart::RevisarPr"

class "my_gym_bro::screens::splash_screen.dart::SplashScreen" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "my_gym_bro::screens::splash_screen.dart::SplashScreen"

class "my_gym_bro::screens::user_screen.dart::UserScreen" {
  +FlutterSecureStorage storage
  +Widget build()
}

"my_gym_bro::screens::user_screen.dart::UserScreen" o-- "flutter_secure_storage::flutter_secure_storage.dart::FlutterSecureStorage"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "my_gym_bro::screens::user_screen.dart::UserScreen"

class "my_gym_bro::service::auth_service.dart::AuthService" {
  -String _baseUrl
  -String _firebaseToken
  +FlutterSecureStorage storage
  +Future<String?> createUser()
  +Future<String?> login()
  +Future<dynamic> logout()
  +Future<String> readToken()
}

"my_gym_bro::service::auth_service.dart::AuthService" o-- "flutter_secure_storage::flutter_secure_storage.dart::FlutterSecureStorage"
"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "my_gym_bro::service::auth_service.dart::AuthService"

class "my_gym_bro::service::leer_json_service.dart::LeerJsonService" {
  +Future<Ejercicio> fetchEjercicio()
}

"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "my_gym_bro::service::leer_json_service.dart::LeerJsonService"

class "my_gym_bro::service::notifications_service.dart::NotificationsService" {
  {static} +GlobalKey<ScaffoldMessengerState> messengerKey
  {static} +dynamic showSnackbar()
}

"my_gym_bro::service::notifications_service.dart::NotificationsService" o-- "flutter::src::widgets::framework.dart::GlobalKey<ScaffoldMessengerState>"

class "my_gym_bro::service::peticiones_service.dart::RutinaService" {
  -String _baseUrl
  +Listas controller
  +FlutterSecureStorage storage
  +bool isLoading
  +bool isSaving
  +Future<dynamic> loadRutinas()
  +Future<dynamic> loadPr()
  +Future<dynamic> saveOrCreateRutina()
  +Future<String> updateRutina()
  +Future<String> createRutina()
  +Future<dynamic> deleteRutina()
  +Future<dynamic> saveOrCreatePr()
  +Future<String> createPr()
  +Future<String> updatePr()
}

"my_gym_bro::service::peticiones_service.dart::RutinaService" o-- "my_gym_bro::models::listas.dart::Listas"
"my_gym_bro::service::peticiones_service.dart::RutinaService" o-- "flutter_secure_storage::flutter_secure_storage.dart::FlutterSecureStorage"
"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "my_gym_bro::service::peticiones_service.dart::RutinaService"

class "my_gym_bro::theme::app_theme.dart::AppTheme" {
  {static} +Color primaryOrange
  {static} +Color primaryBlue
  {static} +Color primaryDarkOrange
  {static} +Color primaryDarkBlue
  {static} +ThemeData lightTheme
}

"my_gym_bro::theme::app_theme.dart::AppTheme" o-- "dart::ui::Color"
"my_gym_bro::theme::app_theme.dart::AppTheme" o-- "flutter::src::material::theme_data.dart::ThemeData"

class "my_gym_bro::ui::input_decorations.dart::InputDecorations" {
  {static} +InputDecoration authInputDecoration()
}

class "my_gym_bro::widgets::auth_background.dart::AuthBackground" {
  +Widget child
  +Widget build()
}

"my_gym_bro::widgets::auth_background.dart::AuthBackground" o-- "flutter::src::widgets::framework.dart::Widget"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "my_gym_bro::widgets::auth_background.dart::AuthBackground"

class "my_gym_bro::widgets::auth_background.dart::_HeaderIcon" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "my_gym_bro::widgets::auth_background.dart::_HeaderIcon"

class "my_gym_bro::widgets::auth_background.dart::_PurpleBox" {
  +Widget build()
  -BoxDecoration _blueBackground()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "my_gym_bro::widgets::auth_background.dart::_PurpleBox"

class "my_gym_bro::widgets::auth_background.dart::_Bubble" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "my_gym_bro::widgets::auth_background.dart::_Bubble"

class "my_gym_bro::widgets::card_container.dart::CardContainer" {
  +Widget child
  +Widget build()
  -BoxDecoration _createCardShape()
}

"my_gym_bro::widgets::card_container.dart::CardContainer" o-- "flutter::src::widgets::framework.dart::Widget"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "my_gym_bro::widgets::card_container.dart::CardContainer"

class "my_gym_bro::widgets::card_swiper.dart::CardSwiper" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "my_gym_bro::widgets::card_swiper.dart::CardSwiper"

class "my_gym_bro::widgets::edit_row_repe_kg.dart::EditRowRepeKg" {
  +RowRepKg rowRepKg
  +List<RowRepKg> list
  +Widget build()
}

"my_gym_bro::widgets::edit_row_repe_kg.dart::EditRowRepeKg" o-- "my_gym_bro::models::row_rep_kg.dart::RowRepKg"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "my_gym_bro::widgets::edit_row_repe_kg.dart::EditRowRepeKg"

class "my_gym_bro::widgets::entreno_card.dart::EntrenoCard" {
  +Rutina rut
  +Widget build()
  -BoxDecoration _cardBorders()
}

"my_gym_bro::widgets::entreno_card.dart::EntrenoCard" o-- "my_gym_bro::models::rutina.dart::Rutina"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "my_gym_bro::widgets::entreno_card.dart::EntrenoCard"

class "my_gym_bro::widgets::entreno_card.dart::_editButton" {
  +Rutina rut
  +State<_editButton> createState()
}

"my_gym_bro::widgets::entreno_card.dart::_editButton" o-- "my_gym_bro::models::rutina.dart::Rutina"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "my_gym_bro::widgets::entreno_card.dart::_editButton"

class "my_gym_bro::widgets::entreno_card.dart::_editButtonState" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "my_gym_bro::widgets::entreno_card.dart::_editButtonState"

class "my_gym_bro::widgets::entreno_card.dart::_backgroundImage" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "my_gym_bro::widgets::entreno_card.dart::_backgroundImage"

class "my_gym_bro::widgets::row_repe_kg.dart::RowRepeKg" {
  +List<RowRepKg> list
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "my_gym_bro::widgets::row_repe_kg.dart::RowRepeKg"


@enduml